Add an experimental PulseAudio module. Already compiles, doesn't work yet.

diff --git a/herrie/configure b/herrie/configure
--- a/herrie/configure
+++ b/herrie/configure
@@ -143,7 +143,7 @@ do
 		unset CFG_XSPF
 		;;
 
-	ao|null|oss|sdl)
+	ao|null|oss|pulse|sdl)
 		CFG_AO=$1
 		;;
 	
@@ -334,6 +334,16 @@ oss)
 		CFLAGS_config="-DOSS_DEVICE=\\\"/dev/dsp\\\""
 		;;
 	esac
+	;;
+pulse)
+	CFLAGS="$CFLAGS -DBUILD_PULSE"
+	CFLAGS_audio_output_pulse="`pkg-config --cflags libpulse-simple`"
+	if [ $? -ne 0 ]
+	then
+		echo "Error: PulseAudio not found"
+		exit 1
+	fi
+	LDFLAGS="$LDFLAGS `pkg-config --libs libpulse-simple`"
 	;;
 sdl)
 	CFLAGS="$CFLAGS `sdl-config --cflags`"
